version: '3.8'

services:

  mongodb:
    container_name: mongodb-links
    image: mongo:latest
    restart: always
    ports:
      - 5674:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db

  mongo-express:
    container_name: mongo-express-links
    image: mongo-express:latest
    restart: always
    ports:
      - 1754:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb


volumes:
  mongo-data:
    driver: local
